# Dependencies
#markdown:         redcarpet
rouge:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Alejandro Centurion
tagline:          'A Jekyll theme'
description:      'Desarrollador JAVA, Estudiante de Programacion en la UNSAM'
url:              https://acenturion.github.io/
baseurl:          https://acenturion.github.io/

author:
  name:           'Alejandro Centurion'
  url:            https://www.linkedin.com/in/alejandro-centurion

paginate:         1

# Custom vars
version:          1.0

github:          
  repo:          https://github.com/acenturion/
