name:               "Alejandro Centurion"
description:        "Desarrollador Java"

url:                ""
author:             "acenturion"
email:              "alejandrocenturion@outlook.com"
gravatar_hash:      "7c1a4f4318f4376ee9fe27b52a467763"
email:              "alejandrocenturion@outlook.com"
github:             "acenturion"
linkedin:           "alejandro-centurion"


disqus_shortname:   "acenturion"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-9505.jpg"

paginate:           3
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Acerca de mi"
    href:           "/about"
  - name:           "Contacto"
    href:           "/contact"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate