# Dependencies
#markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Alejandro Centurion
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://acenturion.github.io/
baseurl:          https://acenturion.github.io/

author:
  name:           'Alejandro Centurion'
  url:            https://www.linkedin.com/in/alejandro-centurion

paginate:         5

# Custom vars
version:          1.0

github:
  repo:          https://github.com/acenturion/
